<a href="https://colab.research.google.com/github/aditya-kote2005/DSBDA_Lab_Practical/blob/main/Practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('wheather_data.csv')

In [ ]:
df.head()

,location,current,error
0,"{'name': 'Abohar', 'region': 'Punjab', 'countr...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
1,"{'name': 'Adoni', 'region': 'Andhra Pradesh', ...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
2,"{'name': 'Agartala', 'region': 'Tripura', 'cou...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
3,"{'name': 'Agra', 'region': 'Uttar Pradesh', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
4,"{'name': 'Ahmedabad', 'region': 'Gujarat', 'co...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN

In [ ]:
df.head(10)

,location,current,error
0,"{'name': 'Abohar', 'region': 'Punjab', 'countr...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
1,"{'name': 'Adoni', 'region': 'Andhra Pradesh', ...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
2,"{'name': 'Agartala', 'region': 'Tripura', 'cou...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
3,"{'name': 'Agra', 'region': 'Uttar Pradesh', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
4,"{'name': 'Ahmedabad', 'region': 'Gujarat', 'co...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
5,"{'name': 'Ahmednagar', 'region': 'Gujarat', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
6,"{'name': 'Aizawl', 'region': 'Mizoram', 'count...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
7,"{'name': 'Ajmer', 'region': 'Rajasthan', 'coun...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
8,"{'name': 'Akola', 'region': 'Maharashtra', 'co...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
9,"{'name': 'Alappuzha', 'region': 'Kerala', 'cou...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN

In [ ]:
df.tail()

,location,current,error
116,"{'name': 'Guwahati', 'region': 'Assam', 'count...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
117,"{'name': 'Gwalior', 'region': 'Madhya Pradesh'...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
118,"{'name': 'Hajipur', 'region': 'Bihar', 'countr...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
119,"{'name': 'Haldia', 'region': 'West Bengal', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
120,"{'name': 'Hapur', 'region': 'Uttar Pradesh', '...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN

In [ ]:
df.tail(10)

,location,current,error
111,"{'name': 'Gulbarga', 'region': 'Karnataka', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
112,"{'name': 'Guna', 'region': 'Madhya Pradesh', '...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
113,"{'name': 'Guntakal', 'region': 'Andhra Pradesh...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
114,"{'name': 'Guntur', 'region': 'Andhra Pradesh',...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
115,"{'name': 'Gurgaon', 'region': 'Haryana', 'coun...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
116,"{'name': 'Guwahati', 'region': 'Assam', 'count...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
117,"{'name': 'Gwalior', 'region': 'Madhya Pradesh'...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
118,"{'name': 'Hajipur', 'region': 'Bihar', 'countr...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
119,"{'name': 'Haldia', 'region': 'West Bengal', 'c...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN
120,"{'name': 'Hapur', 'region': 'Uttar Pradesh', '...","{'last_updated_epoch': 1682924400, 'last_updat...",NaN

In [ ]:
df.shape

(121, 3)

In [ ]:
df.describe()

,location,current,error
count,117,117,4
unique,116,111,1
top,"{'name': 'Durgapur', 'region': 'West Bengal', ...","{'last_updated_epoch': 1682924400, 'last_updat...","{'code': 1006, 'message': 'No matching locatio..."
freq,2,2,4

In [ ]:
df.columns

Index(['location', 'current', 'error'], dtype='object')

In [ ]:
df.isnull().sum()

location      4
current       4
error       117
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  117 non-null    object
 1   current   117 non-null    object
 2   error     4 non-null      object
dtypes: object(3)
memory usage: 3.0+ KB

In [ ]:
df.dtypes

location    object
current     object
error       object
dtype: object